.github/workflows/merged.yml
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLoginBuild.xcscheme
Tests/Test Plans/OneLoginUI.xctestplan
fastlane/Fastfile

We’ve been blocked deploying builds to Testflight in Staging and Build because the github build agents were timing out or failing UITests.
This PR fixes that problem, using Xcode 14.3.1 with iOS 16.4.

ci: fixing deploy workflow

---

OneLogin.xcodeproj/project.pbxproj
fastlane/Fastfile

When deploying builds of the app to Testflight for One Login Staging and Build the build was rejected because an entitlement for camera usage was not given a camera use description.
Furthermore, the build automatically rejected by App Store Connect is still counted but not exposed through the App Store Connect interface or API. Retrying the deploy action then created conflicts as the incremented build number created in the workflow was already accounted for on the App Store Connect side.
~- [] Written Unit and Integration tests if needed~

ci: adding camera use description

---

OneLogin.xcodeproj/project.pbxproj
fastlane/Fastfile

When deploying builds of the app to Testflight for One Login Staging the build was rejected because an entitlement for camera usage was not given a camera use description.

ci: adding camera usage for staging

---

.github/CODEOWNERS

Aligns code ownership on this repository with documentation here https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3791945770/Mobile+Platform+repositories+and+Github+Teams
I've checked things I think are relevant on this change. 

Add mobile-platform team as codeowners on iOS one login app repository

---

OneLogin.xcodeproj/project.pbxproj
OneLoginBuild.entitlements
OneLoginStaging.entitlements
Sources/Application/SceneDelegate.swift
Sources/Onboarding/AuthenticationCoordinator.swift
Sources/Onboarding/MainCoordinator.swift
Sources/Utilities/OnboardingViewControllerFactory.swift
Tests/UnitTests/Onboarding/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Onboarding/MainCoordinatorTests.swift
Tests/UnitTests/Onboarding/Welcome/IntroViewControllerTests.swift
Tests/UnitTests/Utilities/OnboardingViewControllerFactoryTests.swift

This PR is to enable universal linking into the One Login app from domains for staging and build.
Much of the qualifying of the returned query parameters i.e. `authorizationCode` and `state` are handled as part of the [authentication package](https://github.com/govuk-one-login/mobile-ios-authentication)

feat: enabling universal link

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Errors/GenericErrorViewModel.swift
Sources/Errors/UnableToLoginErrorViewModel.swift
Sources/Onboarding/AuthenticationCoordinator.swift
Sources/Onboarding/Welcome/OneLoginIntroViewModel.swift
Sources/Utilities/ErrorPresenter.swift
Tests/UITests/LoginUITests.swift
Tests/UITests/ScreenObjects/App/ErrorScreen.swift
Tests/UITests/ScreenObjects/App/LoginModal.swift
Tests/UITests/ScreenObjects/App/LoginModalSecondScreen.swift
Tests/UITests/ScreenObjects/App/TokensScreen.swift
Tests/UITests/ScreenObjects/App/WelcomeScreen.swift
Tests/UITests/ScreenObjects/ScreenObject.swift
Tests/UnitTests/Errors/UnableToLoginErrorViewModelTests.swift
Tests/UnitTests/Mocks/Sessions+Services/MockLoginSession.swift
Tests/UnitTests/Onboarding/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Utilities/ErrorPresenterTests.swift

This PR shows an "Unable to log in" error screen when a `LoginError` is thrown from the [authentication package](https://github.com/govuk-one-login/mobile-ios-authentication)

feat: show unable to login error screen

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updating to the latest common UI package commit which had a breaking change for the One Login repo to do with using the `viewIsAppearing` lifecycle event when running on versions of Xcode below 15.
~- [] Written Unit and Integration tests if needed~

fix: updating to latest ui common package commit

---

OneLogin.xcodeproj/project.pbxproj
Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Errors/NetworkConnectionErrorViewModel.swift
Sources/Utilities/ErrorPresenter.swift
Tests/UnitTests/Errors/NetworkConnectionErrorViewModelTests.swift
Tests/UnitTests/Utilities/ErrorPresenterTests.swift

_This PR created a network connection error screen, which is ready to be used when an network connection error is thrown._

feat: network connection error screen

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Onboarding/AuthenticationCoordinator.swift
Sources/Onboarding/MainCoordinator.swift
Tests/UnitTests/Mocks/Sessions+Services/MockLoginSession.swift
Tests/UnitTests/Onboarding/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Onboarding/MainCoordinatorTests.swift

This PR displays a network connection error screen when a user is offline and a network connection error is thrown. Updates to the [Authentication package](https://github.com/govuk-one-login/mobile-ios-authentication/pull/22) mean that errors are now owned by the package, `AuthenticationCoordinator` has been updated to catch these specific errors. 
The cancelation of web authentication modal is now properly handled as well. 

feat: displaying network connection error and handling cancellation of modal

---

.github/workflows/merged.yml

We have been using a third-party GitHub action for storing the secrets from AWS secrets manager but there's an official Amazon action for this purpose which is properly supported.

fix: use AWS defined action for storing secrets from secret manager

---

.github/workflows/merged.yml

The way our AWS secrets are stored in our workflows changed slightly when changing the action to an officially supported AWS action. We were not accounting for this but this PR fixes that reference.

fix: amending github env variable references

---

OneLogin.xcodeproj/project.pbxproj
Sources/Onboarding/OnboardingCoordinator.swift
Sources/Resources/cy-GB.lproj/InfoPlist.strings
Sources/Resources/en.lproj/InfoPlist.strings
Sources/Utilities/LAContexting.swift
Tests/UnitTests/Mocks/Sessions+Services/MockLAContext.swift
Tests/UnitTests/Onboarding/OnboardingCoordinatorTests.swift

This PR implements Local Authentication for iOS devices using Face ID at the point of enrolment. When the user selects "Use Face ID" on the enrolment screen primary button, they will need to perform local authentication in order to move to the home screen, failing local authentication will keep them on the enrolment screen.

feat: enrol user in Face ID local authentication from enrolment screen

---

Sources/Login/LoginCoordinator.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockDefaultsStore.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSecureStoreService.swift

This PR redirects a returning user to the signin page should a `SecureStoreError` be thrown when attempting to retrieve tokens

feat: user sees sign in page when app fails to retrieve tokens from secure store

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Login/EnrolmentCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Utilities/Storage/UserStorable.swift
Sources/Utilities/Storage/UserStorage.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockUserStore.swift

In the case that a user has a passcode set on their phone, but no biometrics enrolled, ensure that a private encryption key can be created and saved to the secure enclave. 
This particular change was necessary due to a possible Apple bug wherein our access controls for the keychain were not being honoured when creating keys if no biometrics were enrolled.  Thus we reinitialize the SecureStorage with appropriate controls in that case.

fix: allow storage of private keys when no biometrics are enrolled

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Analytics/Onboarding/BiometricEnrollmentAnalyticsScreen.swift
Sources/Analytics/Onboarding/InformationAnalytics.swift
Sources/Analytics/Onboarding/IntroAnalytics.swift
Sources/Application/Environment/AppEnvironment.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Login/ViewModels/OneLoginIntroViewModel.swift
Sources/Utilities/Analytics/AnalyticsCenter.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UnitTests/Errors/GenericErrorViewModelTests.swift
Tests/UnitTests/Errors/NetworkConnectionErrorViewModelTests.swift
Tests/UnitTests/Errors/UnableToLoginErrorViewModelTests.swift
Tests/UnitTests/Login/ViewModels/FaceIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/OneLoginIntroViewModelTests.swift
Tests/UnitTests/Login/ViewModels/PasscodeInformationViewModelTests.swift
Tests/UnitTests/Login/ViewModels/TouchIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/UnlockScreenViewModelTests.swift

Add new required parameters to all analytics.   Update to use LoggableScreenV2, and add new screen_id parameter to Sing In page.

feat: implement ga4 schema signin in page

---

Sources/Analytics/Onboarding/InformationAnalytics.swift
Sources/Login/ViewModels/PasscodeInformationViewModel.swift
Sources/Utilities/Analytics/AnalyticsCenter.swift
Tests/UnitTests/Login/ViewModels/PasscodeInformationViewModelTests.swift

This adds GA4 analytics to the passcode information screen, when users do not have a passcode on their device 
https://github.com/govuk-one-login/mobile-ios-one-login-app/assets/117986969/a30817b6-819b-4c5d-ad8b-e09acc01d034
- ~~[ ] Met all accessibility requirements?~~
- ~~[ ] Checked dynamic type sizes are applied~~
- ~~[ ] Checked VoiceOver can navigate your new code~~
- ~~[ ] Checked a user can navigate only using a keyboard around your new code~~

feat: initial implementation of GA4 for screen

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml

Update GitHub workflows to use commit shas instead of versions.
[DCMAW-8673](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/440?quickFilter=1326&selectedIssue=DCMAW-8673)
[DCMAW-8673]: https://govukverify.atlassian.net/browse/DCMAW-8673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: update workflows to use commit shas instead of versions

---

Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Errors/GenericErrorViewModel.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Utilities/Factories/ErrorPresenter.swift
Tests/UnitTests/Errors/GenericErrorViewModelTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/MockAnalyticsService.swift
Tests/UnitTests/Utilities/ErrorPresenterTests.swift

This logs and sends the screenErrorView and tracks the button event for GA4 for the generic error page.
- ~~[ ] Met all accessibility requirements?~~
- ~~[ ] Checked dynamic type sizes are applied~~
- ~~[ ] Checked VoiceOver can navigate your new code~~
- ~~[ ] Checked a user can navigate only using a keyboard around your new code~~

feat: implement GA4 schema on the generic error page

---

Sources/Analytics/Onboarding/BiometricEnrollmentAnalyticsScreen.swift
Sources/Login/ViewModels/TouchIDEnrollmentViewModel.swift
Tests/UnitTests/Login/ViewModels/TouchIDEnrollmentViewModelTests.swift

Add GA4 analytics and screen_id to touch-id opt in screen

feat:  Implement GA4 schema on the Touch ID opt-in page

---

Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Errors/NetworkConnectionErrorViewModel.swift
Tests/UnitTests/Errors/GenericErrorViewModelTests.swift
Tests/UnitTests/Errors/NetworkConnectionErrorViewModelTests.swift

Updated to GA4 schema.  This involved replacing ScreenView with ErrorScreenView so we could pass a reason, as well as adding the designated screen id

feat: dcmaw-8421. Implement ga4 schema network connection error page

---

Sources/Analytics/Onboarding/BiometricEnrollmentAnalyticsScreen.swift
Sources/Login/ViewModels/FaceIDEnrollmentViewModel.swift
Tests/UnitTests/Login/ViewModels/FaceIDEnrollmentViewModelTests.swift

Add GA4 analytics and screen_id to face-id opt in screen

feat:  add GA4 analytics (screen_id) to face id enrollment screen

---

Sources/Login/ViewModels/FaceIDEnrollmentViewModel.swift
Sources/Login/ViewModels/TouchIDEnrollmentViewModel.swift
Sources/Resources/cy-GB.lproj/InfoPlist.strings
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Tests/UnitTests/Login/ViewModels/FaceIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/TouchIDEnrollmentViewModelTests.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift

This PR updates the Welsh copy for Face and Touch ID to not be translated. It also updates some English and Welsh copy for the Face/Touch ID enrolment body text and changes the 'use passcode' copy to 'maybe later'. 

chore: updates copy to not translate brand names (e.g. Face ID / Touch ID) AND updates CTA text

---

Sources/Analytics/Onboarding/IntroAnalytics.swift
Sources/Application/SceneDelegate.swift
Sources/Application/SceneLifecycle.swift
Tests/UnitTests/Application/SceneLifecycleTests.swift

Add GA4 analytics for splash screen.  Since we don't have access to the splash screens viewController, send the screen
tracking event after app launch event but before intro screen tracking event.

feat: implement ga4 schema on splash page

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Application/TokenHolder.swift
Sources/Login/LoginCoordinator.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Application/TokenHolderTests.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Login/EnrolmentCoordinatorTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Mocks/OutdatedTokenResponse.json
Tests/UnitTests/Mocks/ReturnTypes/MockTokenResponse.swift

Initialising the `NetworkClient` from the networking package with an `AuthenticationProvider`

feat: initialise NetworkClient on login flow completion

---

OneLogin.xcodeproj/project.pbxproj
Tests/UnitTests/Application/TokenHolderTests.swift
Tests/UnitTests/Login/EnrolmentCoordinatorTests.swift
Tests/UnitTests/Mocks/ReturnTypes/MockTokenResponse.swift
Tests/UnitTests/Mocks/ReturnTypes/OutdatedTokenResponse.json
Tests/UnitTests/Mocks/ReturnTypes/TokenResponse.json
fastlane/Fastfile

The AppAuth library creates a Date object from a JSON `expiry_date` property. This Date object is initialised using the current time and date and sets a time based on the number value in the JSON property. This option is not available in swift when using JSONDecoder.
This PR uses a custom decoding strategy to achieve this to mirror the behaviour of the AppAuth library.

refactor: improve tests involving assertions on Token expiry

---

OneLogin.xcodeproj/project.pbxproj
PrivacyInfo.xcprivacy

Added privacy manifest with `NSPrivacyAccessedAPITypes` in line with Apple's new policy. API types included as per Apple's email are:
- `NSPrivacyAccessedAPICategoryFileTimestamp`
- `NSPrivacyAccessedAPICategoryUserDefaults`
- `NSPrivacyAccessedAPICategoryDiskSpace`
- `NSPrivacyAccessedAPICategorySystemBootTime`

build: adding privacy file with API declarations

---

Sources/Application/Environment/AppEnvironment.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift

This is a fix for passing the locale to the browser when privacy policy link is opened in the browser

fix: adds locale when opening privacy policy link

---

OneLogin-Info.plist
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Extensions/CustomTypes/LoginSessionConfiguration+OneLogin.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift

In the previous work to set up a feature flag for using the STS authorization service the token endpoint was not included as needing specific configuration. This PR amends that with a change to use the latest version of the authentication package where the `idToken` is optional.

fix: STS token error

---

Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift

Correcting rebasing mistake to on build configuration tests.

fix: correcting build configuration test

---

OneLogin.xcodeproj/project.pbxproj
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Home/TabbedView.xib
Sources/Screens/Home/TabbedViewController.swift
Sources/Screens/Home/TabbedViewModel.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/Views/TabbedTableViewCell.swift
Sources/Tabs/Views/TabbedViewCellModel.swift
Sources/Tabs/Views/TabbedViewSectionHeader.swift
Sources/Tabs/Views/TabbedViewSectionHeader.xib
Sources/Views/Components/SignInView.swift
Sources/Views/Components/SignInView.xib
Sources/Views/Components/SignInViewModel.swift
Tests/UITests/LoginUITests.swift
Tests/UITests/ScreenObjects/App/HomeScreen.swift
Tests/UITests/ScreenObjects/App/LoginModal.swift
Tests/UnitTests/Login/HomeCoordinatorTests.swift
Tests/UnitTests/Screens/TabbedViewControllerTests.swift

Create a new TabbedViewController, that holds a tableview of grouped inset style.
Create a header view to hold the user's email address.
Create supporting view models, etc., in anticipation of populating Home and Profile tabs.

feat: dcmaw-8725 home and profile pages

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Application/SceneLifecycle.swift
Sources/Login/LoginCoordinator.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Application/SceneLifecycleTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift

Wait for biometric verification asynchronously.  This prevents it from blocking the main thread, which was causing the OS to kill the app due to unresponsiveness.
Also snuck in fix for repeated tabs appearing when the user returned the app to the foreground after the access token had expired

fix: dcmaw-8998 app crash when timing out face id prompt 

---

Sources/Application/MainCoordinator.swift
Sources/Login/LoginCoordinator.swift

Fixes an issue where the login view was not dismissed if the app was sent to the background before the user re-authenticated with local auth - in this case by causing the local auth to fail.  This caused a mostly invisible nav controller to overaly the tabs, preventing user interaction.
Now when the app returns from the background and local auth is attempted, the login coordinator will dismiss it's root view controller if local auth is successful
Also changed this dismissal to be non-animated to remove a visual artifact
~~- [ ] Checked a user can navigate only using a keyboard …

fix: dcmaw-8935-returning-user-boot-unlock-issue

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Login/EnrolmentCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Login/OnboardingCoordinator.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Tabs/WalletCoordinator.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift

Previously the "Sign in" button on the intro screen was not disabled when interacted with and could produce incorrect behaviour if the user interacted with the button again while the authentication modal was launching.
This PR implements disabling the button and reenabling it when the authentication modal is dismissed.

feat: disable/enable sign in buttton

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/MainCoordinator.swift
Sources/Application/TokenHolder.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Screens/DeveloperMenu/DeveloperMenuViewController.swift
Sources/Screens/Tabs/TabbedViewController.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Utilities/JWT/IdTokenPayload.swift
Sources/Utilities/JWT/JWKInfo.swift
Sources/Utilities/JWT/JWTVerifier.swift
Sources/Utilities/JWT/KeyVerifier.swift
Sources/Utilities/JWT/TokenVerifier.swift
Sources/Utilities/Storage/UserStorable.swift
Sources/Views/Components/SignInView.swift
Sources/Views/Components/SignInView.xib
Sources/Views/Components/SignInViewModel.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Mocks/Sessions+Services/MockTokenVerifier.swift
Tests/UnitTests/Mocks/Sessions+Services/Networking/MockJWKSResponse.swift
Tests/UnitTests/Screens/DeveloperMenuViewControllerTests.swift
Tests/UnitTests/Tabs/HomeCoordinatorTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift
Tests/UnitTests/Utilities/JWTVerifierTests.swift

After successful login, decode the idToken to extract the e-mail, and display on the home page
Added additional functionality to JWTVerifier to decode the idToken without performing verification, since at the point of decoding, the idToken will already have been verified, whether it has been freshly update from BE or retrieved from secure store (as we wouldn't store an unverified token).  This is to prevent the need from having to make another JWKS call every time we decode.
Also refactored so that the initial biometrics/passcode request is for the idToken, not the access token.   The access token is retrieved from the secure store when the Developer Menu is visited, as that is when it is actually required.  This will invoke another biometric auth request, as that is the nature of how …

feat:  dcmaw-8544 user can see email on home page

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Analytics/Onboarding/IntroAnalytics.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Login/ViewModels/FaceIDEnrollmentViewModel.swift
Sources/Login/ViewModels/LoginLoadingViewModel.swift
Sources/Login/ViewModels/OneLoginIntroViewModel.swift
Sources/Login/ViewModels/PasscodeInformationViewModel.swift
Sources/Login/ViewModels/TouchIDEnrollmentViewModel.swift
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Unlock/UnlockScreenViewModel.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Login/ViewModels/LoginLoadingViewModelTests.swift
Tests/UnitTests/Login/ViewModels/PasscodeInformationViewModelTests.swift
Tests/UnitTests/Login/ViewModels/TouchIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/UnlockScreenViewModelTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/MockAnalyticsService.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift

Previously, we had not implemented a loading screen for the first time user login journeys into the app which interacts with the web auth server. Ideally we would give the user sufficient feedback about network requests completing and disable the UI. This PR implements the loading screen for the first time user login journeys.

feat: login loading screen

---

Sources/Login/AuthenticationCoordinator.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift

Fire a trackButtonEvent when the user cancels on the login modal.
Since the button itself can't be accessed, this is done when a "userCancelled" error is returned by the Authentication framework, which amounts to the same thing

feat:  Add GA4 analytics to cancel button on login modal

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Screens/Tabs/TabbedViewController.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Utilities/Storage/UserStorable.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift

When the user signs out, the modal to select analytics permissions is only evident immediately after sign out and does not persist through the app being terminated and relaunched.
This PR amends that bug through a [fix to the logging package](https://github.com/govuk-one-login/mobile-ios-logging/pull/44) so we can effectively reset the analytics permissions for the user when they sign out of the app. Meaning they're prompted to accept/decline analytics permissions any time they come back to the app home page if they haven't set that preference

fix: reset analytics permissions

---

Sources/Application/MainCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Utilities/JWT/JWTVerifier.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift

Refactor to handle errors in a more granular manner, restoring previous secure store handling scheme and adding JWT verification errors.
Add unit tests to cover new scenarios

fix:  dcmaw-9297 Handle errors in a more granular manner

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Application/SceneDelegate.swift
Sources/Login/LoginCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Utilities/Storage/UserStorable.swift
Sources/Utilities/Storage/UserStorage.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSecureStoreService.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift

This PR adds a check in sceneDidEnterBackground to see if the user is a returning user. If they are, then the unlock screen is shown when switching apps. If not, i.e they haven't logged in, then the screen the user was last on is used. 
- <s>[ ] Met all accessibility requirements?

feat: doesn't always use unlock screen for snapshot when going to background

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Application/Environment/FlagManager.swift
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsBuild.json
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsStaging.json
Sources/Errors/SignoutErrorViewModel.swift
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Tabs/ProfileCoordinator.swift
Sources/Utilities/Factories/ErrorPresenter.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSecureStoreService.swift
Tests/UnitTests/Screens/Profile/SignoutErrorViewModelTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift
Tests/UnitTests/Utilities/ErrorPresenterTests.swift

If sign out fails due to an error on deletion, present an error page with a button exiting the app
For testing, I have added a feature flag that can toggle the deletion error being thrown, as the actual likelihood it will fail is close to zero.  This likelihood will change (slightly) once wallet integration is completed.

feat:  dcmaw 8933 sign out error page

---

Sources/Application/MainCoordinator.swift
Sources/Errors/SignoutErrorViewModel.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Tabs/WalletCoordinator.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Screens/Profile/SignoutErrorViewModelTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift
fastlane/Fastfile

This PR implements wallet credential deletion when the user selects to sign out of the app. The token information and analytics preferences are also removed.

feat: delete wallet credential on sign out

---

.github/workflows/merged.yml

Adding swiftlint install to see if it helps with deploy problems

fix:  Add swiftlint step to runner

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

When originally integrating the Wallet SDK into the One Login app versioning was not established on the SDK repository.
A back end change, which was considered for the Wallet test app, but not for the One Login app, because of how recently the SDK had been integrated. Was merged and does not allow the One Login app to add credentials to the Wallet in the One Login app.
Updating the One Login app to use semantic versioning from the Wallet SDK will hopefully avoid breaking changes like this in future.

build: adding versioning for wallet SDK

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Extensions/CustomTypes/LoginSessionConfiguration+OneLogin.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Utilities/Storage/UserStorable.swift
Tests/UnitTests/Extensions/CustomTypes/LoginSessionConfigurationTests.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Screens/DeveloperMenuViewControllerTests.swift

Send the persistentSessionId as a `govuk_signin_session_id` query parameter in the STS /authorize request if it exists in open secure store, if not, don't include it.

feat: send persistent session ID in `/authorize` request

---

Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UITests/LoginUITests.swift
Tests/UITests/ScreenObjects/App/LoginModal.swift
Tests/UITests/ScreenObjects/App/WelcomeScreen.swift

Merged tests were broken by changes in #167, this PR fixes those failures.

test: fix configuration and UI tests

---

Sources/Application/MainCoordinator.swift
Sources/Application/SceneDelegate.swift
Sources/Errors/GenericErrorViewModel.swift
Sources/Errors/NetworkConnectionErrorViewModel.swift
Sources/Errors/UnableToLoginErrorViewModel.swift
Sources/Login/LoginCoordinator.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift

Missing implementation detail from #167 for a non-local auth user.

fix: non-local auth user reauth flow

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Login/AuthenticationCoordinator.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift

When login related errors are passed from Auth to STS, STS delivers a  server_error response to the app. In this scenario, we should ensure that the user is shown an appropriate error page. This PR ensures that the required 'Unable to login' error page is shown instead of the generic error page.
~- [ ] Met all accessibility requirements?~
~- [ ] Checked dynamic type sizes are applied~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] Checked a user can navigate only using a keyboard around your new code~

feat: server error

---

Tests/UITests/LoginUITests.swift

UI tests were not updated in the [pull request to add the server error](https://github.com/govuk-one-login/mobile-ios-one-login-app/pull/173), therefore deployment failed. The UI tests have therefore been updated in this PR.
~- [ ] Reviewed your own code to ensure you are following the style guidelines~
~- [ ] Ran the app and tested the feature on a range of device sizes~
~- [ ] Met all accessibility requirements?~
~- [ ] Checked dynamic type sizes are applied~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] …

fix: fixing sever error

---

OneLogin-Info.plist
OneLogin.xcodeproj/project.pbxproj
Sources/Application/Environment/AppEnvironment.swift
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/UpdateAppVersion/UpdateAppViewModel.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UnitTests/Application/AppEnvironmentTests.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/UpdateAppViewModelTests.swift

This PR adds the UI telling the user to update their app version, with the button opening the app store (which needs to be updated in future with the relevant ID for the store listing in DCMAW-9819). In the simulator the link seems to open Safari on the AppStore webpage, on a device, it opens the AppStore's home screen.
Note: This needs manual QA. Adding something like the below to `OnboardingViewControllerFactory` FaceID or TouchID methods (as these are already the same return type as the new screen) is an easy way to manually check
```
let vm = UpdateAppViewModel(analyticsService: analyticsService) {
primaryButtonAction()
}
```

feat: adds update app screen

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/Environment/Configuration/Build.xcconfig
Sources/Application/Environment/Configuration/Debug.xcconfig
Sources/Application/Environment/Configuration/Release.xcconfig
Sources/Application/Environment/Configuration/Staging.xcconfig

This pull request makes no functional change.
It moves configuration outside of the `xcodeproj` file into separate `xcconfig` files.
`xcconfig` files are a better approach as they are smaller and do not often change.
This means changes that occur are easier to spot during code-reviews.

refactor: extract configuration from xcodeproj

---

fastlane/Fastfile

The deployment pipelines for the One Login app have been failing because of a version number conflict.
Initial uploads of the app were against 1.0, but this has been updated to 1.0.0 as part of our work to enforce a minimum app version: [DCMAW-9522](https://govukverify.atlassian.net/browse/DCMAW-9522).
1.0 and 1.0.0 are considered equivalent by the App Store Connect UI.
When requesting a list of previous builds for 1.0.0, no results are returned.
When requesting a list of previous builds for 1.0, results matching both 1.0 and 1.0.0 are returned.
This change ensures that the build number is correctly incremented for 1.0.0 builds as part of the deployment pipeline.
The build number will therefore now no longer conflict with builds that have been uploaded previously.
[DCMAW-9522]: …

ci: fix deployment pipeline

---

OneLogin.xcodeproj/project.pbxproj
Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Errors/SignOutWarningViewModel.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Screens/SignOutConfirmation/SignOutPageViewModel.swift
Sources/Screens/Tabs/HomeTabViewModel.swift
Sources/Screens/Tabs/ProfileTabViewModel.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Application/SceneLifecycleTests.swift
Tests/UnitTests/Errors/GenericErrorViewModelTests.swift
Tests/UnitTests/Errors/NetworkConnectionErrorViewModelTests.swift
Tests/UnitTests/Errors/SignOutWarningViewModelTests.swift
Tests/UnitTests/Errors/UnableToLoginErrorViewModelTests.swift
Tests/UnitTests/Login/ViewModels/FaceIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/LoginLoadingViewModelTests.swift
Tests/UnitTests/Login/ViewModels/OneLoginIntroViewModelTests.swift
Tests/UnitTests/Login/ViewModels/PasscodeInformationViewModelTests.swift
Tests/UnitTests/Login/ViewModels/TouchIDEnrollmentViewModelTests.swift
Tests/UnitTests/Login/ViewModels/UnlockScreenViewModelTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/MockAnalyticsService.swift
Tests/UnitTests/Screens/Home/HomeTabViewModelTests.swift
Tests/UnitTests/Screens/Profile/ProfileTabViewModelTests.swift
Tests/UnitTests/Screens/Profile/SignOutPageViewModelTests.swift

This implements the GA4 schema for the SignOutWarning screen. 
_Note_: the proposed solution in this PR has meant the `SignOutWarningViewModel` has changed from a struct to a class due to having to rework how the taxonomy is set, as the this schema requires an update to set it for 'reauth'. 
**Log for analytics:**
_Screen:_
```
11.1.0 - [FirebaseAnalytics][I-ACS023072] Event logged. Event name, event params: navigation, {
external = false;
ga_debug (_dbg) = 1;
ga_event_origin (_o) = app;
ga_realtime (_r) = 1;
ga_screen (_sn) = you’ve been signed out;
ga_screen_class (_sc) = signOutWarningScreen;
ga_screen_id (_si) = 1423121875559033750;
language = en;
link_domain = mobile.build.account.gov.uk;
organisation = <OT1056>;
primary_publishing_organisation = government digital service - digital …
```

feat: implements GA4 on SignOutWarning screen

---

Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift

Configuration tests were broken by #191 because calling the `/appInfo` endpoint changed from `https://token.(environment).account.gov.uk/appInfo` to `https://mobile.(environment).account.gov.uk/appInfo`
~- [] Written Unit and Integration tests if needed~

fix: config tests

---

fastlane/Fastfile

We have been ignoring all exceptions thrown by the Fastlane `upload_to_testflight` action. The workflow has been failing silently whilst the GitHub action completes.
The workflow will now fail on all thrown exceptions other than an `UnexpectedResponse` where the `code` received in the `error_info` hash does not equal a string from the App Store Connect API describing that:
"You can’t submit a build for testing if another build is already in review. Wait until your other build has been reviewed, and resubmit this build."

ci: prevent silent failures in deploy pipeline

---

OneLogin-Info.plist

A change to requirements in uploading to App Store Connect means a new entry must be added to the app property list file to declare exemption from US encryption export regulations.
https://developer.apple.com/documentation/security/complying-with-encryption-export-regulations

build: adding info plist entry for app encryption

---

.github/workflows/pull-request.yml
MobilePlatformServices/Package.resolved
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Analytics/Tabs/Profile/ProfileTabAnalytics.swift
Sources/Application/SceneDelegate.swift
Sources/Qualification/QualifyingCoordinator.swift
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/SignOutConfirmation/SignOutPageViewModel.swift
Sources/Screens/SignOutConfirmation/WalletSignOutPageViewModel.swift
Sources/Service/WalletAvailabilityService.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Tabs/TabManagerCoordinator.swift
Tests/UnitTests/Application/SceneLifecycleTests.swift
Tests/UnitTests/Application/TabManagerCoordinatorTests.swift
Tests/UnitTests/Login/EnrolmentCoordinatorTests.swift
Tests/UnitTests/Mocks/Sessions+Services/MockWalletAvailabilityService.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift
Tests/UnitTests/Screens/Profile/SignOutPageViewModelTests.swift
Tests/UnitTests/Screens/Profile/WalletSignOutPageViewModelTests.swift
Tests/UnitTests/Service/WalletAvailabilityServiceTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift
Tests/UnitTests/Utilities/Session/PersistentSessionManagerTests.swift

**Ticket Link:** 
[DCMAW-9638](https://govukverify.atlassian.net/browse/DCMAW-9638)
[DCMAW-10090](https://govukverify.atlassian.net/browse/DCMAW-10090)
**Description Of Changes:** 
Amend existing `SignOutPage` into `WalletSignOutPage` - displays when/ if user accessed wallet at some point. Create new `SignOutPage` - displayed only when the user has _never_ accessed wallet.
AC1b, AC2b, AC3b cannot be evidenced - I can quickly show this on a call if needed - those were met.
**Evidence:**
**_[DCMAW-9638](https://govukverify.atlassian.net/browse/DCMAW-9638)_**
https://github.com/user-attachments/assets/7330e38f-2fe4-4030-af0a-bf3da34a76e0
https://github.com/user-attachments/assets/3ccc5096-6b16-4975-9efb-1bda4ed25f5c
https://github.com/user-attachments/assets/06c7ae71-f456-4223-8dad-aa13450ce1 …

feat: Create SignOutPage when wallet not accessed

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/Environment/Configuration/Build.xcconfig
Sources/Application/Environment/Configuration/Debug.xcconfig
Sources/Application/Environment/Configuration/Release.xcconfig
Sources/Application/Environment/Configuration/Staging.xcconfig
Sources/Application/Firebase/BuildConfig/GoogleService-Info.plist
Sources/Application/Firebase/StagingConfig/GoogleService-Info.plist
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
fastlane/Fastfile

App Integrity and subsequent closer management of Firebase has led to new firebase projects.
A change to the app's bundle id is needed in order to align iOS and Android applications from an infrastructure-as-code management perspective.
This PR replaces the plist file for firebase and alters the app bundle id from `uk.gov.one-login${environment}` to `uk.gov.onelogin${environment}` (removing the hyphen "-")

fix: updating bundle id and firebase plist within one login

---

AppIntegrity/Sources/AppIntegrity/ClientAssertionRequest.swift
AppIntegrity/Sources/AppIntegrity/ClientAssertionResponse.swift
AppIntegrity/Sources/AppIntegrity/FirebaseAppIntegrityService.swift
AppIntegrity/Sources/AppIntegrity/ProofOfPossessionProvider.swift
AppIntegrity/Sources/AppIntegrity/URLRequest+Integrity.swift
AppIntegrity/Tests/AppIntegrity/FirebaseAppIntegrityServiceTests.swift
AppIntegrity/Tests/AppIntegrity/Mocks/MockProofOfPossessionProvider.swift
AppIntegrity/Tests/AppIntegrity/URLRequest+IntegrityTests.swift

Sending the App Check token and the public key of the app’s proof-of-possession key pair to the `client-attestion` endpoint in exchange for a client attestation JWT.

feat: implement the request to client-attestion endpoint

---

.github/CODEOWNERS

Add the Mobile Leads GitHub team to the `CODEOWNERS` for this repository.

Add Mobile Leads to CODEOWNERS

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Analytics/AnalyticsPreferenceViewModel.swift
Tests/UITests/LoginUITests.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Analytics/AnalyticsPreferenceViewModelTests.swift

Updated text on analytics permissions screen.

chore: analytics text update

---

OneLogin.xcodeproj/project.pbxproj
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Enrolment/FaceIDEnrolmentViewModel.swift
Sources/Screens/Enrolment/TouchIDEnrolmentViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Enrolment/FaceIDEnrolmentViewModelTests.swift
Tests/UnitTests/Screens/Enrolment/TouchIDEnrolmentViewModelTests.swift

Updated text on the following screens:
- Face ID opt-in
- Touch ID opt-in

chore: update biometrics screen text

---

Sources/Qualification/AppAttestation/AppIntegrityJWT.swift
Tests/UnitTests/Qualification/AppAttestationTests/AppIntegrityJWTTests.swift

The STS base url included in the app integrity proof of possession was missing the `https://` prefix.
This PR amends that incorrect configuration.

fix: updating proof of possession aud claim to sts base url

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/SceneDelegate.swift
Sources/Qualification/QualifyingCoordinator.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift

Wallet deeplinks, triggered when the app is not launched or in the background, have not reached the Wallet SDK in order for the user to acquire a credential. This PR resolves that issue ahead of refactoring some of the code around how the app window functions.

fix: wallet deeplink

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Application/Environment/FlagManager.swift
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsBuild.json
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsStaging.json
Sources/Screens/Tabs/HomeViewController.swift
Sources/Tabs/HomeCoordinator.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UITests/LoginUITests.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift
Tests/UnitTests/Service/WalletAvailabilityServiceTests.swift

Calling the ID Check `continueIdentityCheckIfRequired` API to start an ID Check journey if there is an active session.
This and calling the `getIDCheckCard` API are now based on a feature flag which is set to default off in Build and default on in Staging.

feat: calling ID Check APIs based on feature flag

---

AppIntegrity/.swiftpm/xcode/xcshareddata/xcschemes/AppIntegrity.xcscheme
AppIntegrity/.swiftpm/xcode/xcshareddata/xcschemes/AppIntegrityTests.xcscheme
MobilePlatformServices/.swiftpm/xcode/xcshareddata/xcschemes/MobilePlatformServices.xcscheme
MobilePlatformServices/.swiftpm/xcode/xcshareddata/xcschemes/MobilePlatformServicesTests.xcscheme
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLogin.xcscheme
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLoginBuild.xcscheme
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLoginStaging.xcscheme

Satisfying the Xcode yellow warning to update to the recommended settings in the workspace.
~- [ ] Reviewed your own code to ensure you are following the style guidelines~

build: update to recommended Xcode settings

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/SignOut/WalletSignOutPageViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/SignOut/WalletSignOutPageViewModelTests.swift

Updated strings on sign out page with Wallet.
https://github.com/user-attachments/assets/d5e6a05b-3cd0-41b0-8d67-f977de9ab682

chore: update sign out page (with Wallet)

---

Sources/Screens/SignOut/SignOutPageViewModel.swift
Tests/UnitTests/Screens/SignOut/SignOutPageViewModelTests.swift

DCMAW-10653 | Exploratory testing | Incorrect Bold Text
Changes the body font from bold to regular body on sign out confirmation screen (no wallet)

fix: removed bold weight from signout screen

---

Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsStaging.json
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift

Disabling the CRI Orchestrator feature flag for the Staging app by default.

fix: CRI Orchestrator feature flag off by default

---

Sources/Screens/Enrolment/FaceIDEnrolmentViewModel.swift
Sources/Screens/Enrolment/TouchIDEnrolmentViewModel.swift
Sources/Screens/Errors/AppUnavailableViewModel.swift
Sources/Screens/Errors/UpdateAppViewModel.swift
Sources/Screens/Tabs/SettingsTabViewModel.swift

There are several screens which still make use of view model protocols which have been marked as deprecated in updated versions of the GDSCommon package. This PR removes these and replaces with the new, segregated protocols.

chore: update deprecated view model protocols

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift

Updating strings on Network Error page.
~- [ ] Checked a user can navigate only using a keyboard around your new code~

chore: updating network error page

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Errors/GenericErrorViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Errors/GenericErrorViewModelTests.swift

Updating strings for generic error screen

chore: updating generic error screen

---

Sources/Qualification/AppAttestation/AppIntegrityJWT.swift
Tests/UnitTests/Qualification/AppAttestationTests/AppIntegrityJWTTests.swift

The app integrity spec has been updated to ensure that the client attestation includes a `typ` header equal to `oauth-client-attestation+jwt`. This PR aims to update the PoP accordingly.

feat: added 'typ' to app integrity pop header

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Login/WebAuthenticationService.swift
Sources/Qualification/State/AppQualifyingService.swift
Sources/Service/WalletSessionData+OneLogin.swift
Sources/Tabs/TabManagerCoordinator.swift
Sources/Utilities/Factories/TabbedViewSectionFactory.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift
Sources/Utilities/Storage/Session/SessionManager.swift
Tests/TestPlans/OneLoginUnit.xctestplan
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift
Tests/UnitTests/Utilities/Session/PersistentSessionManagerTests.swift
scripts-configs/sonar-project.properties

Updating the Wallet SDK to the latest version where a bug has been fixed for deleting data in the One Login host app.

fix: update Wallet SDK for data deletion

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Screens/Analytics/AnalyticsPreferenceViewModel.swift
Sources/Views/Buttons/StandardButtonViewModel.swift
Tests/UnitTests/Screens/Analytics/AnalyticsPreferenceViewModelTests.swift

Following a missed requirement in [DCMAW-7383](https://govukverify.atlassian.net/browse/DCMAW-7873), this PR aims to add an accessibility hint to the privacy notice on the Analytics Opt-in page.
~- [ ] Checked dynamic type sizes are applied~
~- [ ] Checked a user can navigate only using a keyboard around your new code~ 
[DCMAW-7383]: https://govukverify.atlassian.net/browse/DCMAW-7383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adding accessibility hint to analytics opt-in page

---

Sources/Application/Environment/Entitlements/OneLoginBuild.entitlements
Sources/Application/Environment/Entitlements/OneLoginDebug.entitlements
Sources/Application/Environment/Entitlements/OneLoginRelease.entitlements
Sources/Application/Environment/Entitlements/OneLoginStaging.entitlements
Sources/Application/OneLogin-Info.plist
Sources/Resources/cy-GB.lproj/InfoPlist.strings
Sources/Resources/en.lproj/InfoPlist.strings

Running the ID Check SDK in the One Login app the SDK does not have the permissions to access the NFC scanner on the device. This PR sets up those permissions in the host app.

chore: ID Check NFC permissions

---

OneLogin.xcodeproj/project.pbxproj
Sources/Screens/Tabs/HomeViewController.swift
Tests/UnitTests/Mocks/Sessions+Services/MockCRIORchestrator.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift

The HomeViewController was not correctly configured to display the ID Check card. This PR amends the configuration in that view controller.

fix: fixed constraints with displaying tableview

---

Sources/Utilities/Storage/DefaultsStorable.swift
Tests/UnitTests/Extensions/UserDefaults+OneLoginTests.swift

DCMAW-12583 Remove persistent session id from user default if user logs out
~~- [] Created a `draft` pull request if it is not yet ready for review~~

fix: remove persistentSessionID on signout

---

MobilePlatformServices/Sources/MobilePlatformServices/App Info/AppInformationProvider.swift
Sources/Qualification/QualifyingCoordinator.swift
Sources/Qualification/State/AppQualifyingService.swift
Tests/UnitTests/Mocks/Qualification/MockQualifyingService.swift
Tests/UnitTests/Qualification/AppQualifyingServiceTests.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift

This PR is to update the app behaviour to surface a network connection error screen when the user is not connected to the internet and they have no app info saved.
https://github.com/user-attachments/assets/b5ba5587-5703-430e-b3c5-30638493ea22

feat: app info network error

---

Sources/Screens/Tabs/HomeViewController.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift

https://github.com/user-attachments/assets/2d8ba73c-f328-4db0-a183-8d04bf1cb5aa

fix: continue proving identity card not on top of the homepage

---

Tests/UITests/LoginUITests.swift
Tests/UITests/ScreenObjects/App/ErrorScreen.swift
Tests/UITests/ScreenObjects/App/HomeScreen.swift
Tests/UITests/ScreenObjects/App/LoginModal.swift
Tests/UITests/ScreenObjects/App/WelcomeScreen.swift
Tests/UITests/ScreenObjects/ScreenObject.swift

Removing use of the deprecated error screen for a newer version of the screen from our common package has inadvertently broken our UI tests.
This PR fixes them.

fix: UI tests for GDSErrorScreen

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsBuild.json
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsStaging.json
Sources/Screens/Tabs/HomeView.xib
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UITests/LoginUITests.swift
Tests/UITests/ScreenObjects/App/HomeScreen.swift
Tests/UITests/ScreenObjects/App/LoadingScreen.swift
Tests/UITests/ScreenObjects/App/LoginModal.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift

Following branding updates, our UI tests have broken. This PR fixes that.
This PR also matches our local feature flags to that served by the backend appInfo endpoint.

fix: new branding UI tests

---

OneLogin.xcodeproj/project.pbxproj
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/IntegrationConfig/IntegrationAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift

Updated the minimum iOS version for the Strategic app from iOS 14 to iOS 15

chore: update minimum required OS to iOS 15

---

.github/workflows/deploy.yml

Fixes deployment failure of [previous PR](https://github.com/govuk-one-login/mobile-ios-one-login-app/pull/332) to add a badge to the app icons

fix: adding dependency for badges into deploy workflow

---

.github/workflows/pull-request.yml
.github/workflows/unit-test.yml
Sources/Screens/Unlock/UnlockScreenViewController.swift
Tests/UnitTests/Screens/Unlock/UnlockScreenViewControllerTests.swift

Using VoiceOver on the Unlock Screen allows interacting with the main app context which in the window below the unlock screen in the scene, this is a security vulnerability. 

fix: unlock screen voiceover

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift

fix: incorrect privacy notice footer text

---

Sources/Application/Environment/AppEnvironment.swift
Sources/Application/Environment/FlagManager.swift
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsBuild.json
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsIntegration.json
Sources/Application/SupportingFiles/FeatureFlags/FeatureFlagsStaging.json
Sources/Screens/Tabs/HomeViewController.swift
Sources/Utilities/Storage/Session/Authorization/TokenHolder.swift
Tests/ConfigTests/OneLoginBuildConfig/OneLoginBuildAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginIntegrationConfig/OneLoginIntegrationAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginReleaseConfig/OneLoginReleaseAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginStagingConfig/OneLoginStagingAppEnvironmentTests.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift
Tests/UnitTests/Qualification/AppQualifyingServiceTests.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift
Tests/UnitTests/Tabs/HomeCoordinatorTests.swift
Tests/UnitTests/Tabs/SettingsCoordinatorTests.swift
Tests/UnitTests/Utilities/JWTVerifierTests.swift
Tests/UnitTests/Utilities/Session/Authorization/TokenHolderTests.swift

Removing the feature flag for calling APIs on the CRI Orchestrator, this is not included in the /appInfo file which determines feature flags for the app.

chore: remove cri orchestrator feature flag

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

_Thank you for your contribution to the project._
Bumping version number to fix the below bug: 
https://govukverify.atlassian.net/browse/DCMAW-13395

fix: version bump for idcheck sdk bug (rescan docs)

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Screens/Tabs/HomeViewController.swift
Tests/UnitTests/Mocks/Sessions+Services/MockCRIORchestrator.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift

When the ID Check journey completes through a successful or abort flow the ID Check card should be removed from the table view.

fix: ensuring card hides when needed

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Intro/OneLoginIntroViewModel.swift
Sources/Screens/Unlock/UnlockScreenViewController.swift
Sources/Screens/Unlock/UnlockScreenViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Intro/OneLoginIntroViewModelTests.swift
Tests/UnitTests/Screens/Unlock/UnlockScreenViewControllerTests.swift

- **No announcement for GOV.UK logo**
https://github.com/user-attachments/assets/67b53cd5-3c18-4229-b96a-ff8a49e9e809
- **Added announcement to loading label on splash screen**
_Note - presenting the screen was temporarily changed in order to manually test announcement on loading text. Unsure as to whether the voiceover will ever reach this text on the actual splash screen as this is always overshadowed by local auth prompt._
https://github.com/user-attachments/assets/2db8b71a-f62b-4610-96ce-148126e3e04e

feat: do not announce branded items on the splash page

---

Sources/Login/LoginCoordinator.swift
Sources/Screens/Errors/SignOutWarningViewModel.swift
Sources/Screens/Tabs/HomeViewController.swift
Sources/Views/Buttons/AnalyticsButtonViewModel.swift

Owing to a change to `GDSInformationViewController` (typealias for `GDSCentreAlignedScreen`) we need to account for button loading state changes which have been implemented as part of refactoring that view controller.
https://github.com/user-attachments/assets/720b80f3-6ee0-4ce8-9a44-6b2145cf3b55

fix: reauth button state

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/SceneDelegate.swift
Sources/Extensions/UserDefaults+AppIntegrity.swift
Sources/Login/EnrolmentCoordinator.swift
Sources/Screens/Enrolment/BiometricsEnrolmentViewModel.swift
Sources/Utilities/OneLoginEnrolmentManager.swift
Sources/Utilities/Storage/DefaultsStorable.swift
Sources/Utilities/Storage/OneLoginSecureStoreManager.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift
Tests/UnitTests/Utilities/OneLoginSecureStoreManagerTests.swift
Tests/UnitTests/Utilities/Session/PersistentSessionManagerTests.swift

Removing all local auth after logging into the app was causing a crash because we were cycling secure store keys.
This is a hangover from using the secure store access level `currentBiometricsOrPasscode` where we have now moved to `.anyBiometricsOrPasscode` so the keys do not need to be cycled when the user logs out.
This incorporates an update to the Wallet SDK for deleting wallet data, which was also previously causing a crash when deleting keys.

fix: remove refresh and delete from secure store manager

---

Sources/Login/EnrolmentCoordinator.swift
Sources/Qualification/State/AppQualifyingService.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift
Sources/Utilities/Storage/Session/SessionManager.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSessionManager.swift
Tests/UnitTests/Qualification/AppQualifyingServiceTests.swift
Tests/UnitTests/Utilities/Session/PersistentSessionManagerTests.swift

During local auth enrolment, if the user sends the app to the background, the app assumes they've selected the 'Skip' option. This PR aims to fix this by resuming the enrolment flow when the app is brought back to the foreground.
https://github.com/user-attachments/assets/432f8b42-3f63-45b0-8269-c68d3047c351

fix: local auth bug

---

Sources/Screens/Errors/UpdateAppViewModel.swift
Tests/UnitTests/Screens/Errors/UpdateAppViewModelTests.swift

This PR aims to add the `trackEventLink` analytics to the Update App button. All other analytics events for this screen have already been implemented.
This PR also updates the URL used for the primary button. It now opens the actual app listing within the app store instead of the app store homepage.
https://github.com/user-attachments/assets/fe2c905c-9bd1-4e5e-9b24-a7e1eeeb17c7

feat: update app analytics

---

Sources/Analytics/Taxonomy/OLTaxonomy.swift
Sources/Screens/Errors/AppUnavailableViewModel.swift
Sources/Screens/Errors/UpdateAppViewModel.swift
Sources/Screens/Tabs/HomeViewController.swift
Sources/Screens/Tabs/SettingsTabViewModel.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/SettingsCoordinator.swift
Sources/Tabs/WalletCoordinator.swift
Tests/UnitTests/Resources/OLStringTests.swift
Tests/UnitTests/Screens/Errors/AppUnavailableViewModelTests.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift
Tests/UnitTests/Screens/Tabs/SettingsTabViewModelTests.swift
Tests/UnitTests/Screens/Tabs/SettingsViewControllerTests.swift
Tests/UnitTests/Tabs/HomeCoordinatorTests.swift
Tests/UnitTests/Tabs/SettingsCoordinatorTests.swift
Tests/UnitTests/Tabs/WalletCoordinatorTests.swift

https://govukverify.atlassian.net/browse/DCMAW-13813
@dylanjames-dd we are seeing that both CRI and IDCheck level 2 and 3 taxonomies are not sending to analytics. This looks like it is due to these values being set in the HomeCoordinator, and by design these can not be overridden. I have a change in this PR similar to how we did in V1 app to keep the IDCheck analytics service separate so that we can send both the home taxonomies and not let that affect the IDCheck analytics.
Alternatively, we could tidy it up if we were able to not have to send the home taxonomies in the HomeCoordinator, but keen to see what you think and if we should loop in analytics team for that decision if we wanted to.

fix: fixing taxonomy overriding

---

LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/LocalAuthenticationWrapper.swift
LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/Protocols/LocalAuthManaging.swift
LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/Protocols/LocalAuthPromptRecorder.swift
LocalAuthenticationWrapper/Tests/LocalAuthenticationWrapperTests/LocalAuthPromptRecorderTests.swift
LocalAuthenticationWrapper/Tests/LocalAuthenticationWrapperTests/Mocks/MockLocalAuthPromptRecorder.swift
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Screens/Errors/LocalAuthErrorScreens/LocalAuthSettingsErrorViewModel.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/SettingsCoordinator.swift
Sources/Tabs/TabManagerCoordinator.swift
Sources/Tabs/WalletCoordinator.swift
Sources/Utilities/LocalAuthServiceWallet.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/LocalAuth/MockLocalAuthManager.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift
Tests/UnitTests/Utilities/LocalAuthServiceWalletTests.swift

Also included:
- fixed isEnrolled implementation to return correct value
- updated settings page url to navigate user to passcode screen rather than our app settings
- tracking of selected tab so we don't re-call the tab selected methods if user presses on already selected tab
- refactoring of existing implementation to remove optionals and unnecessary variables
https://github.com/user-attachments/assets/09b346bf-1fbe-4508-98fd-ccacac31781d

feat: no local auth set-up - error screen

---

OneLogin.xcodeproj/project.pbxproj
Sources/Application/Assets.xcassets/oneLoginLogo.imageset/Contents.json

Updated the logo artwork to preserve vector data to avoid blurriness.

feat: resolve blurry logo

---

Sources/Application/Environment/Properties/OneLoginIntegration-Info.plist
Sources/Application/Environment/Properties/OneLoginRelease-Info.plist

Fixing cert pinning for all domains used in the One Login app and as part of ID Check

fix: cert pinning for ID Check and Int

---

Sources/Extensions/SDKConformances.swift

Adding custom initialiser for WalletEnvironment type

feat: wallet environment initialiser

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Qualification/QualifyingCoordinator.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift

This PR fixes the ReadID landscape bug, where rotation preferences were overridden by UITabBarController. `QualifyingCoordinator` now uses `OrientationFixingTabBarController` which ensures the correct navigation controller handles rotation.
Common PR - https://github.com/govuk-one-login/mobile-ios-common/pull/148/files
When in landscape mode ReadID no longer rotates - <video src="https://github.com/user-attachments/assets/d95e510c-13e0-4fb3-9e05-4a90b12ab6fb">

fix: readid landscape bug

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Tabs/WalletCoordinator.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Tabs/WalletCoordinatorTests.swift

Changing tab name fro 'Wallet' to 'Documents'

chore: update copy on the wallet tab

---

LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/LocalAuthenticationWrapper.swift
LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/Protocols/LocalAuthManaging.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/AppDelegate.swift
Sources/Application/SceneDelegate.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Extensions/CustomTypes/SecureStorable+OneLogin.swift
Sources/Extensions/SDKConformances.swift
Sources/Login/LoginCoordinator.swift
Sources/Login/OnboardingCoordinator.swift
Sources/Qualification/QualifyingCoordinator.swift
Sources/Tabs/SettingsCoordinator.swift
Sources/Tabs/TabManagerCoordinator.swift
Sources/Utilities/LocalAuthServiceWallet.swift
Tests/UnitTests/Application/SceneLifecycleTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Login/OnboardingCoordinatorTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/MockAnalyticsService.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift
Tests/UnitTests/Tabs/SettingsCoordinatorTests.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift

Using the GAnalyticsV2 type which is now part of the Logging package allows us to remove some code around granting/denying analytics and crashlytics permissions as well as removing the passing of the analytics preference store through all of the parent objects.

refactor: use GAnalyticsV2 type

---

Sources/Login/LoginCoordinator.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift

https://github.com/user-attachments/assets/8e99cf0b-2b58-4775-a971-0216fc02aa8e

feat: show non recoverable error after 3rd server error

---

AppIntegrity/Package.swift
AppIntegrity/Sources/AppIntegrity/AppAttestProviderFactory.swift
AppIntegrity/Sources/AppIntegrity/FirebaseAppIntegrityService.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

We were running a very outdated version of the Firebase SDK. This updates to the latest version of the Logging package which in turn has the latest version of the Firebase SDK as it's dependency.

build: update logging package 4.5.2

---

Sources/Extensions/Dictionary+OneLogin.swift

Removing parameter set for `saved_doc_type`.

fix: remove saved_doc_type from analytics parameters

---

Sources/Extensions/Notifications/Notification+Session.swift
Sources/Qualification/State/AppQualifyingService.swift
Sources/Tabs/SettingsCoordinator.swift
Sources/Tabs/TabManagerCoordinator.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift
Tests/UnitTests/Qualification/AppQualifyingServiceTests.swift
Tests/UnitTests/Tabs/SettingsCoordinatorTests.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift
Tests/UnitTests/Utilities/Session/PersistentSessionManagerTests.swift

Moving the sign out functionality to the SettingCoordinator and removing redundant code from the `resumeSession()` API.

refactor: sign out flow

---

Sources/Tabs/WalletCoordinator.swift
Tests/UnitTests/Tabs/WalletCoordinatorTests.swift

Removing a guard let for the optional persistent session id property of the WalletConfigV2.
https://github.com/user-attachments/assets/8e306610-a074-47d4-9a62-73e988a4dd7a

fix: remove guard let for optional persistent session id

---

Sources/Qualification/QualifyingCoordinator.swift
Sources/Tabs/TabManagerCoordinator.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift

Checking if `childCoordinators` contains the coordinator for each tab before making and adding a new one.
Ensuring the completion of the deeplink method only occurs when `addTabs` has finished to remove potential race conditions.
Failing test without new code:
Passing test with new code:

fix: DCMAW-15372 prevent multiple wallet tabs

---

AppIntegrity/Sources/AppIntegrity/FirebaseAppIntegrityService.swift
AppIntegrity/Tests/AppIntegrity/FirebaseAppIntegrityServiceTests.swift
AppIntegrity/Tests/AppIntegrity/Mocks/MockAppCheckVendor.swift
OneLogin.xcodeproj/project.pbxproj
Sources/Login/LoginCoordinator.swift
Sources/Login/WebAuthenticationService.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Login/WebAuthenticationServiceTests.swift

Working on AppIntegrityError type in the AppIntegrity package to include additional reasoning and maintaining the underlying error from the Firebase App Check `limitedUseToken()` API. Also handling the errors appropriately in the One Login code and displaying appropriate login error screens. The table for the error paths can be found on Confluence [here](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3787195450/GOV.UK+One+Login+app+-+Error+handling#App-integrity-check-failures).

feat: rework app integrity errors

---

AppIntegrity/Package.swift
MobilePlatformServices/Package.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Wallet needs functionality in 3.3.0 for better observability of `Networking` ServerErrors. 3.3.0 added conformance of `CustomNSError` to `ServerError` allowing access to the error code from consumers of Networking that depend on it via dependency inversion.

fix: updated to use 3.3.0 of networking as a minimum
