govuk-one-login/mobile-ios-one-login-app

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

PR for adding common package dependency into the one login app 

chore: add common package dependency

---

.github/workflows/merged.yml
fastlane/Fastfile

This PR fixes the merged.yml workflow and Fastfile for uploading builds to Testflight for GOV.UK One Login | Staging 

ci: fixing deploy workflow

---

.github/workflows/merged.yml

Update `AWS-secrets-manager-actions` to version 2.2.1
[DCMAW-6679](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/371?selectedIssue=DCMAW-6679)
[DCMAW-6679]: https://govukverify.atlassian.net/browse/DCMAW-6679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DCMAW-6679] Update AWS Secrets Manager Version

---

.github/workflows/merged.yml
fastlane/Fastfile

This PR builds upon `feat: initiate login (build)` #15 to deploy the build configuration of the app to the `One Login | Build` instance for Testflight use.

ci: deploy build app

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml
.github/workflows/quality-report.yml
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Views/Buttons/AnalyticsButtonViewModel.swift
fastlane/Fastfile

This PR aims to fix the problems in the pipelines using the github build agents. We've had some issues using the github hosted agents in the iOS One Login repo with completion times taking excessively long to complete.
We have been linking to packages through their URLs without their specific git address.

ci: unblocking pipelines 

---

.github/workflows/merged.yml

We have Dependabot set up for this and all other repos, therefore, a step to check the dependencies is now redundant.
~- [ ] Met all of the acceptance criteria specified in the user story on Jira

ci: remove check dependencies

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml
.github/workflows/quality-report.yml

Our actions have run on intel-based build agents. These take a long time to run and are causing test failures which aren't present when running locally.

ci: upgrading runners to arm64

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml
.github/workflows/quality-report.yml

Reverting change to test workflows on arm64 runners.
~- [ ] Reviewed your own code to ensure you are following the style guidelines~
~- [ ] Ran the app and tested the feature on a range of device sizes~

ci: reverting runners to intel based

---

.github/workflows/merged.yml

Missed correcting the signing key password, this PR amends that missed correction.

fix: amending AWS signing key password

---

.github/workflows/merged.yml

The action to store secrets as environment variables was not being explicitly told to parse the json, this PR amends that.

fix: ensuring action parses secrets json to env variables

---

.github/workflows/pull-request.yml

Add a new GitHub Action to the pre merge workflow that will cause the pipeline to fail if the latest SonarCloud check for the pull request fails

[DCMAW-7579] Add SonarQube GitHub Action quality gate check to workflow

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml

As raised by the big ticket here: https://govukverify.atlassian.net/browse/DCMAW-8586 
We have found a fix by removing the files highlighted in the error logs (see branch [here](https://github.com/govuk-one-login/mobile-ios-one-login-app/pull/82/files#diff-b71166ed0f585913318ed46933ff9b12901e211de3ac88c40de03f0a944c0ae0)) https://github.com/govuk-one-login/mobile-ios-one-login-app/actions/runs/8234676232/job/22516945755 
This change needs to be reverted as this was a temporary fix to not block the iOS team.

ci: revert sonar homebrew fix and update to arm runners

---

OneLogin.xcodeproj/project.pbxproj
Sources/Screens/DeveloperMenu/DeveloperMenu.xib
Sources/Screens/DeveloperMenu/DeveloperMenuViewController.swift
Sources/Screens/DeveloperMenu/DeveloperMenuViewModel.swift
Sources/Screens/Tokens/TokensView.xib
Sources/Screens/Tokens/TokensViewController.swift
Sources/Screens/Tokens/TokensViewModel.swift
Sources/Tabs/HomeCoordinator.swift
Tests/UnitTests/Login/HomeCoordinatorTests.swift
Tests/UnitTests/Screens/TokensViewControllerTests.swift

Add an empty Developer Menu modal view, accessible via the Tokens View after logging in.  This will only be accessible in DEBUG builds.

feat: dcmaw-8622 add developer menu

---

Sources/Application/Environment/AppEnvironment.swift
Sources/Application/MainCoordinator.swift
Sources/Screens/DeveloperMenu/DeveloperMenu.xib
Sources/Screens/DeveloperMenu/DeveloperMenuViewController.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Networking/MockURLOpener.swift
Tests/UnitTests/Screens/DeveloperMenuViewControllerTests.swift

Implementing the unsuccessful hello world call which receives a 401 response to the `hello-world/error` endpoint

feat: hello world API unsuccessful request

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Utilities/Storage/UserStorable.swift
Sources/Utilities/Storage/UserStorage.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSecureStoreService.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift

Update SecureStore package to resolve to version 1.0.0
Refactor code to account for new APIs and breaking changes 

feat: dcmaw-9319 secure store breaking changes

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Tabs/WalletCoordinator.swift
override-git-config
store-access-token.sh

https://govukverify.atlassian.net/browse/DCMAW-9252
This PR copies the implementation from https://github.com/govuk-one-login/mobile-id-check-ios/pull/639, to utilise the PAT (stored in the `MODULE_FETCH_TOKEN` GitHub secret) to access code from the `mobile-wallet-ios` repository.

feat: referring to PAT secret to allow wallet integration

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/MainCoordinator.swift
Sources/Application/SceneDelegate.swift
Sources/Application/TokenHolder.swift
Sources/Extensions/String+OneLogin.swift
Sources/Login/AuthenticationCoordinator.swift
Sources/Login/EnrolmentCoordinator.swift
Sources/Login/LoginCoordinator.swift
Sources/Tabs/HomeCoordinator.swift
Sources/Tabs/ProfileCoordinator.swift
Sources/Tabs/WalletCoordinator.swift
Sources/Utilities/UniversalLinkQualifier.swift
Tests/UnitTests/Application/MainCoordinatorTests.swift
Tests/UnitTests/Extensions/StringTests.swift
Tests/UnitTests/Login/AuthenticationCoordinatorTests.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Tabs/HomeCoordinatorTests.swift
Tests/UnitTests/Tabs/ProfileCoordinatorTests.swift
Tests/UnitTests/Tabs/WalletCoordinatorTests.swift
Tests/UnitTests/Utilities/UniversalLinkQualifierTests.swift

Integrate wallet SDK into the One Login app, feeding through universal links to the `WalletSDK` object in the WalletCoordinator so documents can be seen within the One Login app.

feat: integrate wallet SDK

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Tabs/WalletCoordinator.swift

Updated to a more recent version of the Wallet dependency (3.8.0)
DCMAW-10062

feat: update Wallet dependency

---

fastlane/Fastfile

Upgraded to use the latest version of Xcode.
[DCMAW-10178](https://govukverify.atlassian.net/browse/DCMAW-10178)
[DCMAW-10178]: https://govukverify.atlassian.net/browse/DCMAW-10178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: upgrade Xcode version to 15.4

---

MobilePlatformServices/.gitignore
MobilePlatformServices/Package.resolved
MobilePlatformServices/Package.swift
MobilePlatformServices/Sources/MobilePlatformServices/App Info/AppInformationProvider.swift
MobilePlatformServices/Sources/MobilePlatformServices/App Info/AppInformationServicing.swift
MobilePlatformServices/Sources/MobilePlatformServices/App Info/Response Objects/App.swift
MobilePlatformServices/Sources/MobilePlatformServices/App Info/Response Objects/AppInfoResponse.swift
MobilePlatformServices/Sources/MobilePlatformServices/HelloWorld/HelloWorldProvider.swift
MobilePlatformServices/Sources/MobilePlatformServices/HelloWorld/HelloWorldService.swift
MobilePlatformServices/Tests/MobilePlatformServices/AppInformationServiceTests.swift
MobilePlatformServices/Tests/MobilePlatformServices/HelloWorldServiceTests.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/contents.xcworkspacedata
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Application/MainCoordinator.swift
Sources/Screens/DeveloperMenu/DeveloperMenuViewController.swift
Sources/Tabs/HomeCoordinator.swift
Tests/TestPlans/OneLoginUnit.xctestplan
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift
Tests/UnitTests/Mocks/Sessions+Services/MockAppInfoService.swift
Tests/UnitTests/Mocks/Sessions+Services/MockHelloWorldService.swift
Tests/UnitTests/Screens/DeveloperMenuViewControllerTests.swift
Tests/UnitTests/Tabs/HomeCoordinatorTests.swift

**Implements:** [DCMAW-10076](https://govukverify.atlassian.net/browse/DCMAW-10076)
Network requests to the backend (such as hello world, appInfo, etc.) will be encapsulated within Service classes in a new `MobilePlatformServices` module, similar to the pattern used by the ID Check app codebase.
This means that we can extract the details of API calls out of any coordinators / UI logic, and keep the One Login app codebase cleaner.
[DCMAW-10076]: https://govukverify.atlassian.net/browse/DCMAW-10076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: create Service Package

---

MobilePlatformServices/Sources/MobilePlatformServices/HelloWorld/HelloWorldService.swift
Sources/Utilities/JWT/JWKInfo.swift
Tests/UnitTests/Utilities/Session/Authorization/TokenHolderTests.swift
Tests/UnitTests/Utilities/Session/Authorization/URLRequest+AuthorizationTests.swift

Updated code to pass linting since the latest release of SwiftLint:
https://github.com/realm/SwiftLint/releases/tag/0.57.0

ci: swiftlint failures

---

fastlane/Fastfile

Upgraded to use the latest version of Xcode.

ci: update pipelines to use Xcode 16

---

AppIntegrity/Sources/AppIntegrity/ProofOfPossessionProvider.swift

Creating a protocol to have the ability to sign an access token and get a public key
~- [ ] Ran the app and tested the feature on a range of device sizes~
~- [ ] Met all accessibility requirements?~
~- [ ] Checked dynamic type sizes are applied~
~- [ ] Checked VoiceOver can navigate your new code~
~- [ ] Checked a user can navigate only using a keyboard around your new code~ 
~- [ ] Ran the app to ensure that no regressions have been caused by changes during code review.~

feat: creating proof of possession provider

---

.github/workflows/merged.yml
.github/workflows/pull-request.yml
AppIntegrity/Package.swift
AppIntegrity/Sources/AppIntegrity/AppAttestProviderFactory.swift
AppIntegrity/Sources/AppIntegrity/AppIntegrityProvider.swift
AppIntegrity/Sources/AppIntegrity/FirebaseAppIntegrityService.swift
AppIntegrity/Tests/AppIntegrity/FirebaseAppIntegrityServiceTests.swift
AppIntegrity/Tests/AppIntegrity/Mocks/MockAppCheckVendor.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLogin.xcscheme
OneLogin.xcodeproj/xcshareddata/xcschemes/OneLoginBuild.xcscheme
Sources/Application/AppDelegate.swift
Sources/Application/Environment/Configuration/Build.xcconfig

The bulk of this ticket has already been done in a [previous PR](https://github.com/govuk-one-login/mobile-ios-one-login-app/pull/203/files#diff-5706497a63689b6917dcb7e7f4056829d83d5069ea8974e176efa58828f994e4). This PR mainly adds the debug secrets value to the merged workflow to enable app checks during automation testing.

feat: calling firebase api for app integrity check

---

fastlane/Fastfile

A final piece of configuration renaming was missed as part of #225. This PR corrects the Fastfile to detect the correct configuration for the app. From "Debug_Build" to "Build.

ci: fix deploy configuration

---

.github/workflows/deploy.yml

Calling a Fastlane action requires specific command formatting, having a space between the parameter name and it's argument results in an error. This PR addresses that issue merged in #227

fix: removes spacing in deploy workflow

---

Sources/Screens/Tabs/HomeViewController.swift
Tests/UnitTests/Screens/Tabs/HomeViewControllerTests.swift

Adding closure to reload the table view at the point the CRIOrchestrator call to active session completes.

chore: refine ID Check card

---

.github/workflows/manual-ui-test.yaml
.github/workflows/manual-ui-test.yml
.github/workflows/merged.yml
.github/workflows/ui-test.yml

Setting up ability to run UI tests manually from repository actions. Editing the pull request workflow file to run them for a feature branch is becoming a bit tiresome.
~- [] Ran the app locally ensuring it builds~

ci: manual UI tests

---

.github/workflows/deploy.yml
.github/workflows/merged.yml
.github/workflows/pull-request.yml
fastlane/Fastfile

ci: update Xcode and iOS version
Updating to the latest versions of Xcode and iOS to reflect local development environment.
~- [ ] Ran the tests locally ensuring they pass on Build~

ci: update xcode version

---

OneLogin.xcodeproj/project.pbxproj
Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Tabs/SettingsCoordinatorTests.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift
Tests/UnitTests/Utilities/Session/Authorization/TokenHolderTests.swift

feat: copy change on signout warning screen

---

Gemfile.lock

The xcresult_to_junit fastlane plugin has an updated version, this PR updates to that version.

ci: update xcresult_to_junit fastlane plugin

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Errors/DataDeletedWarningViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Errors/DataDeletedWarningViewModelTests.swift

Copy changes for both with/without wallet

feat: updated copy on deletion warning screen

---

fastlane/Fastfile

Adding xcargs to _all_ test lanes after forgetting in the previous PR #288 

ci: adding xcargs to all test lanes

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Firebase/BuildConfig/GoogleService-Info.plist
Sources/Application/Firebase/StagingConfig/GoogleService-Info.plist
Sources/Login/EnrolmentCoordinator.swift
Sources/Login/WebAuthenticationService.swift
Sources/Qualification/State/AppQualifyingService.swift
Tests/UnitTests/Login/AuthenticationServiceTests.swift
Tests/UnitTests/Login/EnrolmentCoordinatorTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSessionManager.swift
Tests/UnitTests/Qualification/AppQualifyingServiceTests.swift

DCMAW-11743
- updated GoogleService-Info.plist files 
- updated script to upload dsym files to firebase
- updated to secure store 1.1.2
~~- [ ] Created a `draft` pull request if it is not yet ready for review-~~
~~- [] Ran the app and tested the feature on a range of device sizes~~
~~Please include iPod Touch, iPhone SE and iPhone 11 as a minimum.~~
~~- [ ] Written Unit and Integration tests if needed~~

feat: log secure store errors to firebase

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Application/Environment/Configuration/Build.xcconfig
Sources/Application/Environment/Configuration/Debug.xcconfig
Sources/Application/Environment/Configuration/Integration.xcconfig
Sources/Application/Environment/Configuration/Release.xcconfig
Sources/Application/Environment/Configuration/Staging.xcconfig
Sources/Application/OneLogin-Info.plist
Sources/Extensions/SDKConformances.swift
Tests/ConfigTests/BuildConfig/BuildAppEnvironmentTests.swift
Tests/ConfigTests/IntegrationConfig/IntegrationAppEnvironmentTests.swift
Tests/ConfigTests/StagingConfig/StagingAppEnvironmentTests.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift

Correcting endpoints passed to the ID Check SDK.

fix: configuration corrections for id check

---

Sources/Analytics/Errors/ErrorAnalytics.swift
Sources/Analytics/Taxonomy/OLTaxonomy.swift
Sources/Screens/Errors/LocalAuthErrorScreens/LocalAuthErrorViewModel.swift
Tests/UnitTests/Screens/Errors/LocalAuthErrorScreenTests/LocalAuthErrorViewModelTests.swift

This PR aims to implement analytics events on the ‘You need to update your phone settings error’ screen, covering both the Face ID and Touch ID variations. 
TouchID
FaceID
TouchID
FaceID
TouchID
FaceID

feat: local auth error analytics

---

Sources/Login/LoginCoordinator.swift
Sources/Qualification/QualifyingCoordinator.swift
Sources/Screens/Errors/DataDeletedWarningViewModel.swift
Sources/Screens/Errors/GenericErrorViewModel.swift
Sources/Screens/Errors/NetworkConnectionErrorViewModel.swift
Sources/Screens/Errors/SignOutErrorViewModel.swift
Sources/Screens/Errors/SignOutWarningViewModel.swift
Sources/Screens/Errors/UnableToLoginErrorViewModel.swift
Sources/Tabs/TabManagerCoordinator.swift
Tests/UnitTests/Login/LoginCoordinatorTests.swift
Tests/UnitTests/Qualification/QualifyingCoordinatorTests.swift
Tests/UnitTests/Screens/Errors/DataDeletedWarningViewModelTests.swift
Tests/UnitTests/Screens/Errors/GenericErrorViewModelTests.swift
Tests/UnitTests/Screens/Errors/NetworkConnectionErrorViewModelTests.swift
Tests/UnitTests/Screens/Errors/SignOutErrorViewModelTests.swift
Tests/UnitTests/Screens/Errors/SignOutWarningViewModelTests.swift
Tests/UnitTests/Screens/Errors/UnableToLoginErrorViewModelTests.swift
Tests/UnitTests/Tabs/TabManagerCoordinatorTests.swift

refactor: remove deprecated GDSErrorViewController

---

.github/workflows/config-test.yml
.github/workflows/deploy.yml
.github/workflows/merged-main.yml
.github/workflows/merged.yml
.github/workflows/pull-request.yml
.github/workflows/unit-test.yml

Correcting workflows now that we have successfully deployed to the production instance of the app.

chore: correct workflows for merge to develop and main

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Periodic update of the SDKs to keep alignment up-to-date

chore: updating ID Check SDK 7.4.1

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/SceneDelegate.swift
Sources/Extensions/CustomTypes/AnalyticsService+GDS.swift
Sources/Qualification/QualifyingCoordinator.swift
Sources/Screens/Enrolment/BiometricsEnrolmentViewModel.swift
Tests/UnitTests/Mocks/Sessions+Services/Analytics/MockAnalyticsService.swift
Tests/UnitTests/Qualification/AppAttestationTests/AppIntegrityJWTTests.swift
Tests/UnitTests/Screens/Enrolment/BiometricsEnrolmentViewModelTests.swift

Moving to the new analytics schema v3.1, available [here](https://govukverify.atlassian.net/wiki/spaces/PI/pages/3790995627/GA4+One+Login+Mobile+Application+Data+Schema+V3.1)

build: updating Logging package with adjustments for title parameter

---

Sources/Application/Environment/AppEnvironment.swift
Tests/ConfigTests/OneLoginBuildConfig/OneLoginBuildAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginIntegrationConfig/OneLoginIntegrationAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginReleaseConfig/OneLoginReleaseAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginStagingConfig/OneLoginStagingAppEnvironmentTests.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift

Fixing incorrect accessibility url

fix: accessibility url

---

Sources/Analytics/Onboarding/BiometricEnrolmentAnalytics.swift
Sources/Screens/Enrolment/BiometricsEnrolmentViewModel.swift
Tests/UnitTests/Screens/Enrolment/BiometricsEnrolmentViewModelTests.swift

```
11.2.0 - [FirebaseAnalytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
_mst = 1;
ga_debug (_dbg) = 1;
ga_event_origin (_o) = app;
ga_previous_class (_pc) = loginloadingScreen;
ga_previous_id (_pi) = 6806607324911252495;
ga_previous_screen (_pn) = loading;
ga_realtime (_r) = 1;
ga_screen (_sn) = allow face id;
ga_screen_class (_sc) = faceIDEnrollmentScreen;
ga_screen_id (_si) = 6806607324911252496;
language = en;
organisation = <OT1056>;
primary_publishing_organisation = government digital service - digital identity;
saved_doc_type = undefined;
screen_id = 278e2f53-9a93-4093-9009-b87b33f9e946;
taxonomy_level1 = one login mobile application;
title = allow face id;
}
```
```
11.2.0 - …
```

chore: biometrics wallet copy analytics 

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Extensions/CustomTypes/JWTGenerator+ProofTokenGenerator.swift

Updating to a fix version of the ID Check SDK to correct behaviour around hiding the ID Check card once a journey should be finished.

fix: updating id check sdk for table view fix

---

Sources/Application/Environment/AppEnvironment.swift
Sources/Utilities/Factories/TabbedViewSectionFactory.swift
Tests/ConfigTests/OneLoginBuildConfig/OneLoginBuildAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginIntegrationConfig/OneLoginIntegrationAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginReleaseConfig/OneLoginReleaseAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginStagingConfig/OneLoginStagingAppEnvironmentTests.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift
Tests/UnitTests/Screens/Tabs/SettingsViewControllerTests.swift

https://github.com/user-attachments/assets/5a51af5a-ead5-4446-b02a-901c28575a1a
https://github.com/user-attachments/assets/6bf6a67f-1d77-404d-bdd9-ba3d900f04cf

chore: update manage details redirect link

---

fastlane/Fastfile

Working to fix CI using fastlane where coercing a string into an integer throws and error
~- [] Met all of the acceptance criteria specified in the user story on Jira~

ci: fix increment number to integer

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updating ID Check SDK for fixes ahead of release, also including updating common ui dependency.

build: updating ID Check SDK to 8.3.1 and common dependency

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

chore: update authentication to latest version

---

Sources/Application/OneLogin-Info.plist

Ticket: https://govukverify.atlassian.net/browse/DCMAW-13905
~~- [ ] Written Unit and Integration tests if needed~~

hotfix: pin certs

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updating commons package to get changes to keyboard focus.
https://github.com/user-attachments/assets/82eba1bb-d550-4d8b-afde-fb898ac290da

feat: accessibility - keyboard focus

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

build: update wallet package to 13.7.0

---

LocalAuthenticationWrapper/Sources/LocalAuthenticationWrapper/LocalAuthenticationWrapper.swift
Sources/Utilities/LocalAuthServiceWallet.swift
Tests/UnitTests/Utilities/LocalAuthServiceWalletTests.swift

If running the app on simulator, return true to isEnrolled called from Wallet SDK

chore: load wallet on simulator

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Errors/UnableToLoginErrorViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Errors/UnableToLoginErrorViewModelTests.swift

feat: update sign in error page text

---

OneLogin.xcodeproj/project.pbxproj

chore: increase version to 1.5.0

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Errors/LocalAuthErrorScreens/LocalAuthErrorListView.swift
Sources/Screens/Errors/LocalAuthErrorScreens/LocalAuthSettingsErrorViewModel.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Errors/LocalAuthErrorScreenTests/LocalAuthErrorListViewTests.swift
Tests/UnitTests/Screens/Errors/LocalAuthErrorScreenTests/LocalAuthSettingsErrorViewModelTests.swift

feat: local manager text update

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updating the Wallet SDK and Logging package to allow for correct precedence of parameter merging and new parameters added to events.

build: update wallet sdk and logging package for fixes and extra parameters

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

chore: updating ID Check SDK

---

OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Screens/SignOut/WalletSignOutPageViewModel.swift
Tests/UnitTests/Screens/SignOut/WalletSignOutPageViewModelTests.swift

Resolved by updating to the latest version of wallet sdk

chore: double face id bug

---

Sources/Application/SceneDelegate.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift

refactor: re-order sign out deletion order

---

OneLogin.xcodeproj/project.pbxproj

Updated to 1.6.0 following release of 1.5.0

chore: updating minimum version

---

README.md
docs/how-to/required-software.md
docs/how-to/running-the-code.md
docs/how-to/ways-of-working.md

~- [ ] Ran the app locally ensuring it builds~ 
~- [ ] Ran the tests locally ensuring they pass on Build~
~- [ ] Ran the app and tested the feature on a range of device sizes~

docs: updating readme

---

.github/dependabot.yml

_Thank you for your contribution to the project._
_Please enter a short description of your change here._

ci: use GitHub registry for gitsubmodule updates

---

OneLogin.xcodeproj/project.pbxproj

chore: version bump to 1.7.0

---

OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

build(deps): downgrade id check sdk to 8.19.1

---

.github/workflows/config-test.yml
.github/workflows/deploy.yml
.github/workflows/ui-test.yml
.github/workflows/unit-test.yml
AppIntegrity/Package.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/Application/Environment/AppEnvironment.swift
Sources/Extensions/SDKConformances.swift
Sources/Tabs/WalletCoordinator.swift
Sources/Utilities/Storage/Session/PersistentSessionManager.swift
Sources/Utilities/Storage/Session/SessionManager.swift
Tests/ConfigTests/OneLoginBuildConfig/OneLoginBuildAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginIntegrationConfig/OneLoginIntegrationAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginReleaseConfig/OneLoginReleaseAppEnvironmentTests.swift
Tests/ConfigTests/OneLoginStagingConfig/OneLoginStagingAppEnvironmentTests.swift
Tests/UnitTests/Application/Environment/AppEnvironmentTests.swift
Tests/UnitTests/Mocks/Sessions+Services/Storage/MockSessionManager.swift
Tests/UnitTests/Tabs/WalletCoordinatorTests.swift

release v1.7.0

---

OneLogin.xcodeproj/project.pbxproj

build: bump to 1.8.0

---

Sources/Resources/cy-GB.lproj/Localizable.strings
Sources/Resources/en.lproj/Localizable.strings
Sources/Screens/Errors/SignOutErrorViewModel.swift
Sources/Tabs/SettingsCoordinator.swift
Tests/UnitTests/Resources/LocalizedEnglishStringTests.swift
Tests/UnitTests/Resources/LocalizedWelshStringTests.swift
Tests/UnitTests/Screens/Errors/SignOutErrorViewModelTests.swift

Sign out error screen copy for users who have seen the wallet functionality in the app.

feat: sign out error screen with wallet

---

OneLogin.xcodeproj/project.pbxproj

chore: bump version to 1.11.0

---

AppIntegrity/Package.swift
OneLogin.xcodeproj/project.pbxproj
OneLogin.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updating Wallet SDK and ID Check SDK with the Logging and Common package transient dependencies also updated.
Alongside second level transient dependencies of ReadID, iProov and Firebase.

build: update Wallet SDK (16.40.1) and ID Check SDK (8.37.0)
